language: php
php:
  - '7.1'
  - '7.2'

env:
  - TEST=1env
  - NODE_RELEASE=8.15
  - NOTE_RELEASE=10.15

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE myblog;"
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install ${NODE_RELEASE}
  - npm install

script:
  - make install
  - make check
  - ./vendor/bin/codacycoverage clover ./docs/coverage/xml

